// <auto-generated />
namespace ITrackERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _tty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_tty));
        
        string IMigrationMetadata.Id
        {
            get { return "201702121915161__tty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
